apiVersion: batch/v1
kind: CronJob
metadata:
  name: isbg-train
  namespace: spamprotect
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: isbg
            image: guestros/k8s-docker-spamprotection-rspamd-isbg:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: isbg-credentials
