name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
        - name: isbg
          dockerfile: Dockerfile
          tag: guestros/k8s-docker-spamprotection-rspamd-isbg:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push ${{ matrix.service.name }}
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.service.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ matrix.service.tag }}
        cache-from: type=gha,scope=multiarch
        cache-to: type=gha,mode=max,scope=multiarch
